name: transformer-based-rl
channels:
- pytorch
dependencies:
- python=3.10.9
- anaconda
# - cudatoolkit=10.
- numpy
- pip
- pip:
  - gymnasium==0.28.1
  - pygame==2.4.0
  # - mujoco-py==2.0.2.13
  - numpy==1.24.3
  - torch==2.0.0
  - transformers==4.29.1
  # - wandb==0.9.1