name: transformer-based-rl
channels:
- pytorch
dependencies:
- python=3.8.10
- anaconda
- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym==0.17.2
  - pygame==2.4.0
  - atari-py==0.2.9
  - numpy==1.24.3
  - torch==2.0.0
  - transformers==4.29.1
  - scikit-image==0.21.0
  - wandb==0.9.1